export default function Disclaimer() {
    return (
        <div className="container mx-auto px-4 py-8">
            The information on our site is only directed at professional clients and eligible counterparties and the services or investments referred to on our site are only available to professional clients and eligible counterparties. Retail clients should not rely on the information herein. If you have any doubts about your status you must not access our site.
This website is for information purposes only. Nothing herein shall be construed (i) as an official confirmation of any transaction and/or (ii) as investment advice or a recommendation. Any offer of securities may be made only by means of formal offering documents. Risks are inherent to investments and engaging in any investment activity may expose you to a significant risk of losing all of the property or other assets invested.
The Firm does not utilize a UK sustainable investment label. Any queries on statements indicating or implying a sustainability product should be directed to info@mu-llc.com. Our firm is committed to transparency and accountability in our sustainability practices. All statements regarding the sustainability benefits of our products are based on current data and analysis available at the time of publication. However, sustainability performance can be influenced by various factors beyond our control, and past performance is not necessarily indicative of future results. We encourage our stakeholders to request further information on the product and the firm's sustainability practices from info@mu-llc.com.
​Please note that you are required to have read and accepted the terms of our Privacy Policy & Terms of Use before you are able to access our website.
By clicking “Accept” you have confirmed that you have read, understood and agreed to the legal terms and conditions of this website. You also: (i) Agree that such information will apply to any subsequent access to this website by you, and that all such subsequent access will be subject to the disclaimers, risk warnings and other information set out herein; and (ii) Warrant that no other person will access this website from the same computer and logon as you are currently using.
        </div>
    )